# Generated by Django 3.0.4 on 2020-05-24 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eadmin', '0012_auto_20200524_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStaff',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='Staff Id')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Phone')),
            ],
        ),
    ]
