# Generated by Django 3.0.4 on 2020-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverystaff', '0002_deliverystaff_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystaff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Shop Name'),
        ),
    ]
