# Generated by Django 3.0.4 on 2020-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200528_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_staff',
            field=models.IntegerField(default=0, verbose_name='Delivery Staff'),
        ),
    ]
