# Generated by Django 3.0.4 on 2020-05-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orders_delivery_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
