# Generated by Django 3.0.4 on 2020-05-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_staff',
            field=models.CharField(default='0', max_length=50, verbose_name='Delivery Staff'),
        ),
    ]
