# Generated by Django 3.0.4 on 2020-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='someone@example.com', max_length=50, verbose_name='Email'),
        ),
    ]
