# Generated by Django 3.0.4 on 2020-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200531_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='someone@example.com', max_length=50, null=True, verbose_name='Email'),
        ),
    ]
