# Generated by Django 3.0.3 on 2020-03-13 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0004_auto_20200313_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)], verbose_name='Product name')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter')], max_length=10, verbose_name='Unit(s)')),
                ('details', models.CharField(default='No details are available', max_length=250, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='Details')),
            ],
        ),
    ]
