# Generated by Django 3.0.3 on 2020-03-14 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0006_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocations',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
