# Generated by Django 3.0.4 on 2020-05-24 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0012_auto_20200524_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Invalid price'), django.core.validators.MaxValueValidator(1000, 'Invalid price')], verbose_name='Price'),
        ),
    ]
