# Generated by Django 3.0.4 on 2020-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0014_auto_20200528_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='day',
            field=models.CharField(default=31, editable=False, max_length=5, verbose_name='Day'),
        ),
    ]
