# Generated by Django 3.0.4 on 2020-06-16 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_aadhar'),
        ('eadmin', '0018_auto_20200616_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'Please provide a longer title')])),
                ('complaint', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Explain your issue in atleast 10 chars')])),
                ('reply', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Write your reply in atleast 10 chars')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
