# Generated by Django 3.0.3 on 2020-03-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0004_auto_20200313_0713'),
        ('customer', '0002_auto_20200313_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_type',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='eadmin.Cards', to_field='card_name', verbose_name='Card type'),
        ),
    ]
