# Generated by Django 3.0.4 on 2020-05-28 15:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0014_auto_20200528_2044'),
        ('customer', '0003_auto_20200313_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000, 'Price cannot exceed 10000'), django.core.validators.MinValueValidator(0, 'The minimum price should be 0')], verbose_name='Price')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('delivered_on', models.DateField(verbose_name='Delivered on')),
                ('otp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Invalid OTP Value'), django.core.validators.MaxValueValidator(9999, 'Invalid OTP')], verbose_name='OTP')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Out for delivery', 'Out for delivery')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.Products')),
            ],
        ),
    ]
