# Generated by Django 3.0.4 on 2020-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivered_on',
        ),
        migrations.AddField(
            model_name='orders',
            name='dday',
            field=models.IntegerField(default=0, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='orders',
            name='dmonth',
            field=models.IntegerField(default=0, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='orders',
            name='dyear',
            field=models.IntegerField(default=0, verbose_name='Year'),
        ),
    ]
