# Generated by Django 3.0.4 on 2020-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200531_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=None, max_length=50, verbose_name='Email'),
        ),
    ]
