# Generated by Django 3.0.4 on 2020-06-02 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200531_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar',
            field=models.BigIntegerField(default=1111111111, validators=[django.core.validators.MinValueValidator(111111111111), django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='Aadhar Number'),
            preserve_default=False,
        ),
    ]
