# Generated by Django 3.0.3 on 2020-02-25 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pin',
            field=models.CharField(default='666666', max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='PIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='place',
            field=models.CharField(help_text='Please enter nearby town or place', max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)], verbose_name='Place'),
        ),
    ]
