# Generated by Django 3.0.4 on 2020-05-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_stocks_stockupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Please enter the new stock', verbose_name='Quantity'),
        ),
    ]
