# Generated by Django 3.0.3 on 2020-02-20 07:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, verbose_name='Shop Name')),
                ('shop_id', models.CharField(max_length=20, unique=True, verbose_name='Shop Id')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Phone')),
                ('place', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)], verbose_name='Place')),
            ],
        ),
    ]
