# Generated by Django 3.0.4 on 2020-05-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0011_auto_20200521_1102'),
        ('shop', '0002_auto_20200225_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Please enter the new stock', verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.Products')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StockUpdates', verbose_name='Stock Update ID')),
            ],
        ),
    ]
