# Generated by Django 3.0.4 on 2020-05-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200521_1123'),
        ('deliverystaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystaff',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
            preserve_default=False,
        ),
    ]
