# Generated by Django 3.0.4 on 2020-05-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverystaff', '0003_auto_20200531_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystaff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
