# Generated by Django 3.0.3 on 2020-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0003_auto_20200225_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shop', 'Shop'), ('customer', 'Customer')], default='shop', max_length=10, verbose_name='User Role'),
        ),
    ]
