# Generated by Django 3.0.3 on 2020-03-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.Cards', to_field='card_name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.Products', to_field='name')),
            ],
            options={
                'unique_together': {('card_name', 'product')},
            },
        ),
    ]
