# Generated by Django 3.0.4 on 2020-03-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200313_0738'),
        ('eadmin', '0009_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='day',
            field=models.CharField(default=24, editable=False, max_length=5, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', to_field='card_number'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together=set(),
        ),
    ]
