# Generated by Django 3.0.4 on 2020-05-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0010_auto_20200324_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='day',
            field=models.CharField(default=21, editable=False, max_length=5, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='month',
            field=models.CharField(default=5, editable=False, max_length=20, verbose_name='month'),
        ),
    ]
