# Generated by Django 3.0.4 on 2020-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0011_auto_20200521_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='day',
            field=models.CharField(default=24, editable=False, max_length=5, verbose_name='Day'),
        ),
    ]
