# Generated by Django 3.0.4 on 2020-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0013_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='day',
            field=models.CharField(default=28, editable=False, max_length=5, verbose_name='Day'),
        ),
    ]
