# Generated by Django 3.0.4 on 2020-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0015_auto_20200531_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shop', 'Shop'), ('staff', 'Delivery Staff')], default='shop', max_length=10, verbose_name='User Role'),
        ),
    ]
