# Generated by Django 3.0.4 on 2020-06-16 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_aadhar'),
        ('eadmin', '0017_auto_20200602_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='day',
            field=models.CharField(default=16, editable=False, max_length=5, verbose_name='Day'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('complaint', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Explain your issue in atleast 10 chars')])),
                ('reply', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Write your reply in atleast 10 chars')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
